import React from "react";
import Banner from "components/Banner";
import Firm from "components/Firm";
import Head from "next/head";

const MyComponent = () => {
  return (
    <>
      <Head>
        <title>Lex Gateway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lex.ico" />
      </Head>
      <Banner
        heading="About Us"
        text="Welcome to Lex Gateway"
        image="/images/office3.jpg"
      />
      <Firm />
    </>
  );
};

export default MyComponent;
