import Banner from "components/Banner";
import Contact from "components/contact";
import Head from "next/head";
import React from "react";

const contact = () => {
  return (
    <>
      <Head>
        <title>Lex Gateway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lex.ico" />
      </Head>
      <Contact />
    </>
  );
};

export default contact;
