import type { NextPage } from "next";
import Head from "next/head";
import Attorney from "components/Attorney";
import About from "components/About";
import Areas from "components/Areas";
import Hero from "components/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
      <title>Lex Gateway</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/lex.ico" />
      </Head>
      <Hero />
      <About />
      <Areas />
      <Attorney />
    </>
  );
};

export default Home;
