import Banner from "components/Banner";
import Service from "components/services";
import React from "react";
import Head from 'next/head'
const service = () => {
  return (
    <>
     <Head>
      <title>Lex Gateway</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/lex.ico" />
      </Head>
      <Banner
        heading="Our Services"
        text="Lex Gateway LP is into innovative and customized legal practice with a focus on current areas of law. Our major areas of practice include the following: "
        image="/images/low-key.jpg"
      />
      <Service />
    </>
  );
};

export default service;
