import React from "react";
import Banner from "components/Banner";
import Team from "components/Team";
import { GetStaticProps, NextPage } from "next";
import { teamData } from "../data";
import { ITeam } from "type";
import Head from "next/head";

const team: NextPage<{ teams: ITeam[] }> = ({ teams }) => {
  return (
    <>
      <Head>
        <title>Lex Gateway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lex.ico" />
      </Head>
      <Banner
        heading={"Our Team"}
        text="Meet Whole Team"
        image="/images/office2.jpg"
      />
      <Team teams={teams} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      teams: teamData,
    },
  };
};

export default team;
